address lint errors
src/raie/fetch_database.py:66:5: F841 local variable 'df_ecg' is assigned to but never used
src/raie/fetch_database.py:128:5: F841 local variable 'df_ecg' is assigned to but never used
src/raie/fetch_database.py:236:5: F841 local variable 'df_ecg' is assigned to but never used
src/raie/real_time.py:6:1: F401 'pandas as pd' imported but unused
src/raie/studies.py:4:1: F401 'tempbeat as tb' imported but unused
src/raie/studies.py:6:1: F811 redefinition of unused 'sleepecg' from line 3
src/raie/studies.py:6:1: F401 'raie.methods.martinez2004' imported but unused
src/raie/studies.py:50:9: F821 undefined name 'martinez'